version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8888:80"
    user: "1000:1000"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: 8888
    command: ["pipenv", "run", "python", "simple_web_service.py"]
